#!/usr/bin/env bash
# Omarchy10k — Bash adapter and hook broker
# This file is generated by `omarchy10k init bash` and sourced in .bashrc
# It is the ONLY integration point: eval "$(omarchy10k init bash)"

# Guard: only run in interactive shells
[[ $- == *i* ]] || return 0

# Guard: don't reinitialize
[[ -n "${__O10K_INITIALIZED:-}" ]] && return 0
__O10K_INITIALIZED=1

# ── Paths ──────────────────────────────────────────────────────────────────

__O10K_BIN="${O10K_BIN:-omarchy10k}"
__O10K_DAEMON_BIN="${O10K_DAEMON_BIN:-omarchy10kd}"
__O10K_SOCKET_DIR="${XDG_RUNTIME_DIR:-/tmp}"
__O10K_SOCKET="${__O10K_SOCKET_DIR}/omarchy10k-$$.sock"

# ── Hook Broker ────────────────────────────────────────────────────────────
# Public API for tools (Mise, Atuin, Zoxide, etc.) to register callbacks
# Usage: o10k_hook_add <event> <function_name>
# Events: precmd, preexec, chpwd, shell_exit

declare -a __O10K_HOOKS_precmd=()
declare -a __O10K_HOOKS_preexec=()
declare -a __O10K_HOOKS_chpwd=()
declare -a __O10K_HOOKS_shell_exit=()

o10k_hook_add() {
    local event="$1" fn="$2"
    case "$event" in
        precmd)    __O10K_HOOKS_precmd+=("$fn") ;;
        preexec)   __O10K_HOOKS_preexec+=("$fn") ;;
        chpwd)     __O10K_HOOKS_chpwd+=("$fn") ;;
        shell_exit) __O10K_HOOKS_shell_exit+=("$fn") ;;
        *) echo "omarchy10k: unknown hook event: $event" >&2 ;;
    esac
}

o10k_hook_remove() {
    local event="$1" fn="$2"
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local new=()
    for f in "${hooks[@]}"; do
        [[ "$f" != "$fn" ]] && new+=("$f")
    done
    hooks=("${new[@]}")
}

__o10k_dispatch() {
    local event="$1"; shift
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local fn
    for fn in "${hooks[@]}"; do
        "$fn" "$@" 2>/dev/null
    done
}

# ── Daemon Lifecycle ───────────────────────────────────────────────────────

__o10k_start_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        # Socket exists — check if daemon is alive
        if __o10k_socket_send '{"command":"status"}' >/dev/null 2>&1; then
            return 0
        fi
        rm -f "$__O10K_SOCKET"
    fi

    O10K_PARENT_PID=$$ "$__O10K_DAEMON_BIN" &>/dev/null &
    disown

    # Wait for socket (up to 2s)
    local i=0
    while [[ ! -S "$__O10K_SOCKET" ]] && (( i < 20 )); do
        sleep 0.1
        (( i++ ))
    done
}

__o10k_stop_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        __o10k_socket_send '{"command":"shutdown"}' 2>/dev/null || true
        rm -f "$__O10K_SOCKET"
    fi
}

# Portable Unix socket send — prefers socat, falls back to bash /dev/tcp workaround or python
__o10k_socket_send() {
    local msg="$1"
    if command -v socat &>/dev/null; then
        echo "$msg" | socat -T2 - UNIX-CONNECT:"$__O10K_SOCKET"
    elif command -v python3 &>/dev/null; then
        python3 -c "
import socket, sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(2)
s.connect('$__O10K_SOCKET')
s.sendall(b'$msg\n')
data = b''
while True:
    chunk = s.recv(4096)
    if not chunk: break
    data += chunk
    if b'\n' in data: break
s.close()
sys.stdout.write(data.decode())
" 2>/dev/null
    else
        return 1
    fi
}

# ── Timing ─────────────────────────────────────────────────────────────────

__O10K_CMD_START=0
__O10K_CMD_DURATION=0

__o10k_timer_start() {
    __O10K_CMD_START="${EPOCHREALTIME:-$(date +%s%N)}"
}

__o10k_timer_stop() {
    if [[ "$__O10K_CMD_START" == "0" ]]; then
        __O10K_CMD_DURATION=0
        return
    fi
    local now="${EPOCHREALTIME:-$(date +%s%N)}"
    # EPOCHREALTIME is float seconds; convert to ms
    if [[ "$now" == *.* ]]; then
        local start_s="${__O10K_CMD_START%%.*}"
        local start_us="${__O10K_CMD_START##*.}"
        local now_s="${now%%.*}"
        local now_us="${now##*.}"
        # Pad to 6 digits
        start_us="${start_us}000000"; start_us="${start_us:0:6}"
        now_us="${now_us}000000"; now_us="${now_us:0:6}"
        __O10K_CMD_DURATION=$(( (now_s - start_s) * 1000 + (10#$now_us - 10#$start_us) / 1000 ))
    else
        __O10K_CMD_DURATION=0
    fi
    __O10K_CMD_START=0
}

# ── Chpwd Emulation ───────────────────────────────────────────────────────

__O10K_LAST_PWD="$PWD"

__o10k_check_chpwd() {
    if [[ "$PWD" != "$__O10K_LAST_PWD" ]]; then
        __O10K_LAST_PWD="$PWD"
        __o10k_dispatch chpwd
    fi
}

# ── Prompt Rendering ──────────────────────────────────────────────────────

__O10K_FALLBACK_PS1='\[\e[1;34m\]\w\[\e[0m\] \[\e[1;32m\]❯\[\e[0m\] '

__o10k_render_prompt() {
    local exit_code=$?
    __o10k_timer_stop

    # Dispatch precmd hooks (mise, atuin, zoxide, etc.)
    __o10k_check_chpwd
    __o10k_dispatch precmd

    # Request prompt from daemon
    if [[ -S "$__O10K_SOCKET" ]]; then
        local cols="${COLUMNS:-80}"
        local jobs_count
        jobs_count=$(jobs -p 2>/dev/null | wc -l)

        local request
        request=$(printf '{"cwd":"%s","exit_code":%d,"cmd_duration_ms":%d,"cols":%d,"jobs":%d}' \
            "$PWD" "$exit_code" "$__O10K_CMD_DURATION" "$cols" "$jobs_count")

        local response
        response=$(__o10k_socket_send "$request" 2>/dev/null)

        if [[ -n "$response" ]]; then
            local left
            left=$(echo "$response" | "$__O10K_BIN" parse-prompt 2>/dev/null || echo "$response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('left',''))" 2>/dev/null)
            if [[ -n "$left" ]]; then
                PS1="$left"
                return
            fi
        fi
    fi

    # Fallback prompt if daemon is unreachable
    PS1="$__O10K_FALLBACK_PS1"
}

# ── Preexec ────────────────────────────────────────────────────────────────

__O10K_PREEXEC_READY=0

__o10k_preexec() {
    # Only fire once per command (avoid DEBUG trap re-fires)
    [[ "$__O10K_PREEXEC_READY" == "1" ]] || return
    __O10K_PREEXEC_READY=0
    __o10k_timer_start
    __o10k_dispatch preexec "$BASH_COMMAND"
}

# ── Installation ───────────────────────────────────────────────────────────
# Detects ble.sh and installs hooks via the best available mechanism

__o10k_install_hooks() {
    if [[ -n "${BLE_VERSION:-}" ]] && (( ${BLE_VERSION%%.*} >= 4 )); then
        # ble.sh enhanced mode
        __o10k_install_blesh_hooks
    else
        # Vanilla Bash mode
        __o10k_install_vanilla_hooks
    fi
}

__o10k_install_blesh_hooks() {
    # Register via ble.sh hook system (no PROMPT_COMMAND clobbering)
    blehook PRECMD+='__o10k_render_prompt'
    blehook PREEXEC+='__o10k_preexec_blesh'
    blehook CHPWD+='__o10k_dispatch chpwd'

    # Transient prompt support
    bleopt prompt_ps1_transient='always'
    # The transient content is set dynamically by the renderer

    # Mark preexec ready after each prompt (ble.sh manages this lifecycle)
    blehook PRECMD+='__O10K_PREEXEC_READY=1'
}

__o10k_preexec_blesh() {
    __o10k_timer_start
    __o10k_dispatch preexec "$1"
}

__o10k_install_vanilla_hooks() {
    # Install PROMPT_COMMAND (array-aware for Bash 5.1+)
    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        # PROMPT_COMMAND is already an array
        PROMPT_COMMAND=('__o10k_render_prompt' "${PROMPT_COMMAND[@]}")
    elif [[ -n "${PROMPT_COMMAND:-}" ]]; then
        PROMPT_COMMAND="__o10k_render_prompt;${PROMPT_COMMAND}"
    else
        PROMPT_COMMAND='__o10k_render_prompt'
    fi

    # Install preexec via PS0 (Bash 4.4+) or DEBUG trap
    if (( BASH_VERSINFO[0] > 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 4) )); then
        # PS0 method — fires once per command line, not per simple command
        PS0='$(__o10k_preexec 2>/dev/null)'
    else
        # DEBUG trap fallback — save and chain existing trap
        local existing_trap
        existing_trap=$(trap -p DEBUG | sed "s/trap -- '\\(.*\\)' DEBUG/\\1/")
        if [[ -n "$existing_trap" ]]; then
            trap '__o10k_preexec; '"$existing_trap" DEBUG
        else
            trap '__o10k_preexec' DEBUG
        fi
    fi

    # Mark preexec ready after each prompt render
    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        PROMPT_COMMAND+=('__O10K_PREEXEC_READY=1')
    else
        PROMPT_COMMAND="${PROMPT_COMMAND};__O10K_PREEXEC_READY=1"
    fi
}

# ── Shell Exit ─────────────────────────────────────────────────────────────

__o10k_cleanup() {
    __o10k_dispatch shell_exit
    __o10k_stop_daemon
}

trap __o10k_cleanup EXIT

# ── Init ───────────────────────────────────────────────────────────────────

__o10k_start_daemon
__o10k_install_hooks
