#!/usr/bin/env bash
# Omarchy10k — Bash adapter and hook broker
# This file is generated by `omarchy10k init bash` and sourced in .bashrc
# It is the ONLY integration point: eval "$(omarchy10k init bash)"

# Guard: only run in interactive shells
[[ $- == *i* ]] || return 0

# Guard: don't reinitialize
[[ -n "${__O10K_INITIALIZED:-}" ]] && return 0
__O10K_INITIALIZED=1

# ── Paths ──────────────────────────────────────────────────────────────────

__O10K_BIN="${O10K_BIN:-omarchy10k}"
__O10K_DAEMON_BIN="${O10K_DAEMON_BIN:-omarchy10kd}"
__O10K_SOCKET_DIR="${XDG_RUNTIME_DIR:-/tmp}"
__O10K_SOCKET="${__O10K_SOCKET_DIR}/omarchy10k-$$.sock"

# ── Instant Prompt Cache ──────────────────────────────────────────────────
__O10K_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/omarchy10k"
__O10K_CACHE="${__O10K_CACHE_DIR}/last_prompt"

if [[ -f "$__O10K_CACHE" ]]; then
    PS1=$(<"$__O10K_CACHE")
fi

# ── Shell Integration Guard ───────────────────────────────────────────────
# O10K_SHELL_INTEGRATION=auto|force|off
# auto: emit OSC 133 unless terminal already provides integration
# force: always emit
# off: never emit

__O10K_SHELL_INTEGRATION="${O10K_SHELL_INTEGRATION:-auto}"
__O10K_HAS_TERMINAL_INTEGRATION=0

__o10k_detect_terminal_integration() {
    if [[ "$__O10K_SHELL_INTEGRATION" == "off" ]]; then
        __O10K_EMIT_OSC133=0
        return
    fi
    if [[ "$__O10K_SHELL_INTEGRATION" == "force" ]]; then
        __O10K_EMIT_OSC133=1
        return
    fi
    # Detect known terminal shell integrations
    if declare -F __ghostty_precmd &>/dev/null \
        || declare -F __vte_prompt_command &>/dev/null \
        || declare -F __wezterm_set_user_var &>/dev/null \
        || [[ -n "${KITTY_SHELL_INTEGRATION:-}" ]]; then
        __O10K_HAS_TERMINAL_INTEGRATION=1
        __O10K_EMIT_OSC133=0
    else
        __O10K_EMIT_OSC133=1
    fi
}

__o10k_detect_terminal_integration

# ── Hook Broker ────────────────────────────────────────────────────────────
# Public API for tools (Mise, Atuin, Zoxide, etc.) to register callbacks
# Usage: o10k_hook_add <event> <function_name>
# Events: precmd, preexec, chpwd, shell_exit

declare -a __O10K_HOOKS_precmd=()
declare -a __O10K_HOOKS_preexec=()
declare -a __O10K_HOOKS_chpwd=()
declare -a __O10K_HOOKS_shell_exit=()

o10k_hook_add() {
    local event="$1" fn="$2"
    case "$event" in
        precmd)    __O10K_HOOKS_precmd+=("$fn") ;;
        preexec)   __O10K_HOOKS_preexec+=("$fn") ;;
        chpwd)     __O10K_HOOKS_chpwd+=("$fn") ;;
        shell_exit) __O10K_HOOKS_shell_exit+=("$fn") ;;
        *) echo "omarchy10k: unknown hook event: $event" >&2 ;;
    esac
}

o10k_hook_remove() {
    local event="$1" fn="$2"
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local new=()
    for f in "${hooks[@]}"; do
        [[ "$f" != "$fn" ]] && new+=("$f")
    done
    hooks=("${new[@]}")
}

__o10k_dispatch() {
    local event="$1"; shift
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local fn
    for fn in "${hooks[@]}"; do
        "$fn" "$@" 2>/dev/null
    done
}

# ── Daemon Lifecycle ───────────────────────────────────────────────────────

__o10k_start_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        if __o10k_socket_send '{"command":"status"}' >/dev/null 2>&1; then
            return 0
        fi
        rm -f "$__O10K_SOCKET"
    fi

    O10K_PARENT_PID=$$ "$__O10K_DAEMON_BIN" &>/dev/null &
    disown

    local i=0
    while [[ ! -S "$__O10K_SOCKET" ]] && (( i < 20 )); do
        sleep 0.1
        (( i++ ))
    done
}

__o10k_stop_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        __o10k_socket_send '{"command":"shutdown"}' 2>/dev/null || true
        rm -f "$__O10K_SOCKET"
    fi
}

# ── Bridge Coprocess ──────────────────────────────────────────────────────
# Persistent Rust process that holds a daemon connection and avoids
# fork/exec on every prompt render. Falls back to socket_send if unavailable.

__O10K_BRIDGE_PID=0

__o10k_start_bridge() {
    if (( __O10K_BRIDGE_PID > 0 )) && kill -0 "$__O10K_BRIDGE_PID" 2>/dev/null; then
        return 0
    fi

    coproc __O10K_BRIDGE { "$__O10K_BIN" bridge --socket "$__O10K_SOCKET" 2>/dev/null; }
    __O10K_BRIDGE_PID=$!
}

__o10k_bridge_request() {
    local request="$1"
    if (( __O10K_BRIDGE_PID > 0 )) && kill -0 "$__O10K_BRIDGE_PID" 2>/dev/null; then
        echo "$request" >&"${__O10K_BRIDGE[1]}" 2>/dev/null || {
            __o10k_start_bridge
            echo "$request" >&"${__O10K_BRIDGE[1]}" 2>/dev/null || return 1
        }
        local left
        IFS= read -r -d $'\0' -t 2 -u "${__O10K_BRIDGE[0]}" left 2>/dev/null
        if [[ -n "$left" ]]; then
            PS1="$left"
            { printf '%s' "$PS1" > "$__O10K_CACHE.tmp" && mv "$__O10K_CACHE.tmp" "$__O10K_CACHE"; } 2>/dev/null &
            return 0
        fi
    fi
    return 1
}

# Portable Unix socket send — legacy fallback when bridge is unavailable
__o10k_socket_send() {
    local msg="$1"
    if command -v socat &>/dev/null; then
        echo "$msg" | socat -T2 - UNIX-CONNECT:"$__O10K_SOCKET"
    elif command -v python3 &>/dev/null; then
        python3 -c "
import socket, sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(2)
s.connect('$__O10K_SOCKET')
s.sendall(b'$msg\n')
data = b''
while True:
    chunk = s.recv(4096)
    if not chunk: break
    data += chunk
    if b'\n' in data: break
s.close()
sys.stdout.write(data.decode())
" 2>/dev/null
    else
        return 1
    fi
}

# ── Timing ─────────────────────────────────────────────────────────────────

__O10K_CMD_START=0
__O10K_CMD_DURATION=0
__O10K_LAST_CMD=""
__O10K_NOTIFY_THRESHOLD="${O10K_NOTIFY_THRESHOLD:-10000}"

__o10k_timer_start() {
    __O10K_CMD_START="${EPOCHREALTIME:-$(date +%s%N)}"
}

__o10k_timer_stop() {
    if [[ "$__O10K_CMD_START" == "0" ]]; then
        __O10K_CMD_DURATION=0
        return
    fi
    local now="${EPOCHREALTIME:-$(date +%s%N)}"
    if [[ "$now" == *.* ]]; then
        local start_s="${__O10K_CMD_START%%.*}"
        local start_us="${__O10K_CMD_START##*.}"
        local now_s="${now%%.*}"
        local now_us="${now##*.}"
        start_us="${start_us}000000"; start_us="${start_us:0:6}"
        now_us="${now_us}000000"; now_us="${now_us:0:6}"
        __O10K_CMD_DURATION=$(( (now_s - start_s) * 1000 + (10#$now_us - 10#$start_us) / 1000 ))
    else
        __O10K_CMD_DURATION=0
    fi
    __O10K_CMD_START=0
}

# ── Chpwd Emulation ───────────────────────────────────────────────────────

__O10K_LAST_PWD="$PWD"

__o10k_check_chpwd() {
    if [[ "$PWD" != "$__O10K_LAST_PWD" ]]; then
        __O10K_LAST_PWD="$PWD"
        __o10k_dispatch chpwd
    fi
}

# ── Prompt Rendering ──────────────────────────────────────────────────────

__O10K_FALLBACK_PS1='\[\e[1;34m\]\w\[\e[0m\] \[\e[1;32m\]❯\[\e[0m\] '

__o10k_render_prompt() {
    local exit_code=$?

    # OSC 133;D — mark end of previous command output
    (( __O10K_EMIT_OSC133 )) && printf '\e]133;D;%d\a' "$exit_code"

    __o10k_timer_stop

    # Desktop notification for long-running commands
    if (( __O10K_CMD_DURATION > ${__O10K_NOTIFY_THRESHOLD:-10000} )); then
        printf '\033]777;notify;Command finished;%s took %dms\007' \
            "${__O10K_LAST_CMD:-command}" "$__O10K_CMD_DURATION"
    fi

    printf '\033[?2026h'

    __o10k_check_chpwd
    __o10k_dispatch precmd

    printf '\033]9;4;0\007'

    if [[ -S "$__O10K_SOCKET" ]]; then
        local cols="${COLUMNS:-80}"
        local jobs_count
        jobs_count=$(jobs -p 2>/dev/null | wc -l)

        local si_flag="true"
        (( __O10K_EMIT_OSC133 )) || si_flag="false"

        local request
        request=$(printf '{"cwd":"%s","exit_code":%d,"cmd_duration_ms":%d,"cols":%d,"jobs":%d,"shell_integration":%s}' \
            "$PWD" "$exit_code" "$__O10K_CMD_DURATION" "$cols" "$jobs_count" "$si_flag")

        # Try bridge first (no fork/exec in hot path)
        if __o10k_bridge_request "$request"; then
            printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$PWD"
            printf '\033[?2026l'
            return
        fi

        # Fallback: socket send + parse-prompt
        local response
        response=$(__o10k_socket_send "$request" 2>/dev/null)

        if [[ -n "$response" ]]; then
            local left
            left=$(echo "$response" | "$__O10K_BIN" parse-prompt 2>/dev/null || echo "$response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('left',''))" 2>/dev/null)
            if [[ -n "$left" ]]; then
                PS1="$left"
                { printf '%s' "$PS1" > "$__O10K_CACHE.tmp" && mv "$__O10K_CACHE.tmp" "$__O10K_CACHE"; } 2>/dev/null &
                printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$PWD"
                printf '\033[?2026l'
                return
            fi
        fi
    fi

    PS1="$__O10K_FALLBACK_PS1"
    printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$PWD"
    printf '\033[?2026l'
}

# ── Preexec ────────────────────────────────────────────────────────────────

__O10K_PREEXEC_READY=0

__o10k_preexec() {
    [[ "$__O10K_PREEXEC_READY" == "1" ]] || return
    __O10K_PREEXEC_READY=0

    # OSC 133;C — mark start of command output
    (( __O10K_EMIT_OSC133 )) && printf '\e]133;C\a'

    __O10K_LAST_CMD="$BASH_COMMAND"
    printf '\033]9;4;3\007'
    __o10k_timer_start
    __o10k_dispatch preexec "$BASH_COMMAND"
}

# ── Installation ───────────────────────────────────────────────────────────

__o10k_install_hooks() {
    if [[ -n "${BLE_VERSION:-}" ]] && (( ${BLE_VERSION%%.*} >= 4 )); then
        __o10k_install_blesh_hooks
    else
        __o10k_install_vanilla_hooks
    fi
}

__o10k_install_blesh_hooks() {
    blehook PRECMD+='__o10k_render_prompt'
    blehook PREEXEC+='__o10k_preexec_blesh'
    blehook CHPWD+='__o10k_dispatch chpwd'

    bleopt prompt_ps1_transient='always'

    # Right prompt support via ble.sh
    blehook PRECMD+='__o10k_update_rps1'

    blehook PRECMD+='__O10K_PREEXEC_READY=1'
}

__o10k_preexec_blesh() {
    # OSC 133;C
    (( __O10K_EMIT_OSC133 )) && printf '\e]133;C\a'
    __O10K_LAST_CMD="$1"
    printf '\033]9;4;3\007'
    __o10k_timer_start
    __o10k_dispatch preexec "$1"
}

__o10k_update_rps1() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        local response
        response=$(__o10k_socket_send '{"command":"status"}' 2>/dev/null)
        # Right prompt is rendered by the daemon; extract from response
        if [[ -n "$response" ]]; then
            local right
            right=$(echo "$response" | python3 -c "import sys,json; r=json.load(sys.stdin).get('right',''); print(r if r else '')" 2>/dev/null)
            if [[ -n "$right" ]]; then
                bleopt prompt_rps1="$right"
                return
            fi
        fi
    fi
    bleopt prompt_rps1=""
}

__o10k_install_vanilla_hooks() {
    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        PROMPT_COMMAND=('__o10k_render_prompt' "${PROMPT_COMMAND[@]}")
    elif [[ -n "${PROMPT_COMMAND:-}" ]]; then
        PROMPT_COMMAND="__o10k_render_prompt;${PROMPT_COMMAND}"
    else
        PROMPT_COMMAND='__o10k_render_prompt'
    fi

    if (( BASH_VERSINFO[0] > 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 4) )); then
        PS0='$(__o10k_preexec 2>/dev/null)'
    else
        local existing_trap
        existing_trap=$(trap -p DEBUG | sed "s/trap -- '\\(.*\\)' DEBUG/\\1/")
        if [[ -n "$existing_trap" ]]; then
            trap '__o10k_preexec; '"$existing_trap" DEBUG
        else
            trap '__o10k_preexec' DEBUG
        fi
    fi

    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        PROMPT_COMMAND+=('__O10K_PREEXEC_READY=1')
    else
        PROMPT_COMMAND="${PROMPT_COMMAND};__O10K_PREEXEC_READY=1"
    fi
}

# ── Shell Exit ─────────────────────────────────────────────────────────────

__o10k_cleanup() {
    __o10k_dispatch shell_exit
    # Kill bridge coprocess
    if (( __O10K_BRIDGE_PID > 0 )); then
        kill "$__O10K_BRIDGE_PID" 2>/dev/null
    fi
    __o10k_stop_daemon
}

trap __o10k_cleanup EXIT

# ── Init ───────────────────────────────────────────────────────────────────

[[ -d "$__O10K_CACHE_DIR" ]] || mkdir -p "$__O10K_CACHE_DIR" 2>/dev/null

__o10k_start_daemon
__o10k_start_bridge
__o10k_install_hooks
