#!/usr/bin/env bash
# Omarchy10k — Bash adapter and hook broker
# This file is generated by `omarchy10k init bash` and sourced in .bashrc
# It is the ONLY integration point: eval "$(omarchy10k init bash)"

# Guard: only run in interactive shells. O10K_HARNESS_ONLY=1 opts the
# fixture test harness (tests/vanilla_transient_test.sh) in from a plain
# non-interactive bash; that mode never starts daemons or installs hooks.
[[ $- == *i* || -n "${O10K_HARNESS_ONLY:-}" ]] || return 0

# Guard: don't reinitialize
[[ -n "${__O10K_INITIALIZED:-}" ]] && return 0
__O10K_INITIALIZED=1

# ── Paths ──────────────────────────────────────────────────────────────────

__O10K_BIN="${O10K_BIN:-omarchy10k}"
__O10K_DAEMON_BIN="${O10K_DAEMON_BIN:-omarchy10kd}"
__O10K_SOCKET_DIR="${XDG_RUNTIME_DIR:-/tmp}"
__O10K_SOCKET="${__O10K_SOCKET_DIR}/omarchy10k-$$.sock"

# ── Instant Prompt Cache ──────────────────────────────────────────────────
__O10K_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/omarchy10k"
__O10K_CACHE="${__O10K_CACHE_DIR}/last_prompt"

# PS1 content (daemon/path/branch text) must never undergo parameter or
# command expansion — keep promptvars off for this shell.
shopt -u promptvars

# Ghostty's `keybind = shift+enter=csi:13;2u` sends a CSI-u sequence that
# readline cannot parse — it leaks as literal `;2u` at the prompt. Bind it to
# accept-line (treat Shift+Enter as Enter) in terminals that send it. Harmless
# no-op elsewhere. (Interactive shells only reach this point.)
bind '"\e[13;2u": accept-line' &>/dev/null || true

if [[ -f "$__O10K_CACHE" ]]; then
    PS1=$(<"$__O10K_CACHE")
fi

# ── Terminal Identification ───────────────────────────────────────────────
# Resolves O10K_TERM once per shell. Everything downstream -- the OSC 133
# gate below, the daemon's capability profile, `omarchy10k doctor` -- reads
# this instead of guessing from TERM_PROGRAM.
#
# Guessing from the environment does not work, and foot is why. foot
# DELIBERATELY UNSETS TERM_PROGRAM (its man page lists the variable under
# "Variables unset in the child process"), and Omarchy sets
# term=xterm-256color in foot.ini, so a real foot session looks like this:
#
#     TERM=xterm-256color  COLORTERM=truecolor  (no TERM_PROGRAM at all)
#
# It carries no identifying signal whatsoever. It does answer XTVERSION
# (CSI > q) correctly, so when the environment is inconclusive we ask.

__o10k_probe_xtversion() {
    # The probe talks to /dev/tty directly, so it does NOT care whether
    # stdin or stdout are redirected -- requiring `-t 1` here made the probe
    # bail whenever output was piped, which is most of the ways it gets
    # tested. A usable controlling terminal is the only real requirement;
    # whether we SHOULD probe is the resolver's decision, below.
    [[ -r /dev/tty && -w /dev/tty ]] || return 1

    local saved reply=""
    saved=$(stty -g </dev/tty 2>/dev/null) || return 1
    # A raw tty left behind is the one unacceptable outcome, so restoring it
    # is a trap rather than a trailing statement.
    trap 'stty "$saved" </dev/tty 2>/dev/null' RETURN

    stty raw -echo min 0 time 0 </dev/tty 2>/dev/null || return 1
    printf '\033[>q' >/dev/tty 2>/dev/null || return 1

    # Read byte-by-byte with a timeout on each `read`, which BLOCKS for up to
    # that long -- the whole point. An earlier version polled with `read -N 0`
    # between iterations; that reads zero bytes and returns immediately, so
    # the loop spun out in roughly no time and the reply never arrived. foot
    # was still detected as `unknown` and the bug looked like a probe failure.
    #
    # 80ms for the first byte; once a terminal starts answering the rest
    # follows immediately, so later bytes get a short timeout. A terminal that
    # answers nothing costs 80ms once per shell, never per prompt.
    local ch first=1
    while IFS= read -rsN1 -t "$( ((first)) && echo 0.08 || echo 0.01 )" \
            ch </dev/tty 2>/dev/null; do
        first=0
        reply+="$ch"
        [[ "$reply" == *$'\033\\' || "$reply" == *$'\a' ]] && break
        (( ${#reply} > 128 )) && break   # never read unboundedly
    done

    [[ -n "$reply" ]] || return 1
    printf '%s' "$reply"
}

__o10k_resolve_terminal() {
    # 1. Explicit override, and what the probe writes for later shells.
    if [[ -n "${O10K_TERM:-}" ]]; then
        return
    fi

    # 2. Unambiguous environment. Ghostty -- the common case under Omarchy --
    #    always lands here, so it never pays for the probe.
    if [[ -n "${GHOSTTY_RESOURCES_DIR:-}" || "$TERM" == "xterm-ghostty" ]]; then
        O10K_TERM=ghostty
        # Ghostty publishes its version, so the env path is as informative as
        # a probe would be -- and free.
        [[ -n "${TERM_PROGRAM_VERSION:-}" ]] && O10K_TERM_VERSION="$TERM_PROGRAM_VERSION"
        export O10K_TERM O10K_TERM_VERSION; return
    fi
    if [[ "$TERM" == foot || "$TERM" == foot-* ]]; then
        O10K_TERM=foot; export O10K_TERM; return
    fi
    if [[ -n "${KITTY_WINDOW_ID:-}" || "$TERM" == "xterm-kitty" ]]; then
        O10K_TERM=kitty; export O10K_TERM; return
    fi

    # 3. Probe -- but never through a multiplexer or over ssh, where the
    #    reply describes the wrong terminal and a confident wrong answer is
    #    worse than none.
    # Interactive shells only: a script or a pipeline has no business writing
    # escape sequences at a terminal.
    #
    # NOT skipped over ssh, deliberately. An earlier version skipped it, on
    # the theory that the reply would describe the wrong terminal. The
    # opposite is true: over ssh the pty runs back to the LOCAL terminal,
    # which answers with its real identity -- and that terminal is precisely
    # the one rendering the prompt, so its capabilities are the ones that
    # matter. Environment variables are least trustworthy over ssh, which
    # makes the probe most valuable there.
    #
    # tmux IS skipped: it answers as itself and interposes its own capability
    # set, so the outer terminal's identity would be misleading.
    if [[ $- == *i* || -n "${O10K_FORCE_PROBE:-}" ]] && [[ -z "${TMUX:-}" ]]; then
        local reply name
        reply=$(__o10k_probe_xtversion) || reply=""
        if [[ -n "$reply" ]]; then
            # Strip the DCS envelope, take the leading name token.
            name="${reply#*|}"
            name="${name%%$'\033'*}"
            name="${name%%$'\a'*}"
            name="${name%%[ (]*}"
            case "${name,,}" in
                ghostty|foot|kitty|wezterm|alacritty)
                    O10K_TERM="${name,,}"
                    O10K_TERM_VERSION="${reply#*"$name"}"
                    O10K_TERM_VERSION="${O10K_TERM_VERSION%%$'\033'*}"
                    O10K_TERM_VERSION="${O10K_TERM_VERSION//[()]/}"
                    O10K_TERM_VERSION="${O10K_TERM_VERSION// /}"
                    export O10K_TERM O10K_TERM_VERSION
                    return
                    ;;
            esac
        fi
    fi

    # 4. TERM_PROGRAM, then give up. `unknown` is a real answer: it selects
    #    the conservative capability profile rather than pretending.
    case "${TERM_PROGRAM:-}" in
        ghostty|foot|wezterm|alacritty) O10K_TERM="${TERM_PROGRAM,,}" ;;
        *)                              O10K_TERM=unknown ;;
    esac
    export O10K_TERM
}

__o10k_resolve_terminal

# ── Shell Integration Guard ───────────────────────────────────────────────
# O10K_SHELL_INTEGRATION=auto|force|off
# auto: emit OSC 133 unless terminal already provides integration
# force: always emit
# off: never emit

__O10K_SHELL_INTEGRATION="${O10K_SHELL_INTEGRATION:-auto}"
__O10K_HAS_TERMINAL_INTEGRATION=0

__o10k_detect_terminal_integration() {
    if [[ "$__O10K_SHELL_INTEGRATION" == "off" ]]; then
        __O10K_EMIT_OSC133=0
        return
    fi
    if [[ "$__O10K_SHELL_INTEGRATION" == "force" ]]; then
        __O10K_EMIT_OSC133=1
        return
    fi
    # Detect known terminal shell integrations
    if declare -F __ghostty_precmd &>/dev/null \
        || declare -F __vte_prompt_command &>/dev/null \
        || declare -F __wezterm_set_user_var &>/dev/null \
        || [[ -n "${KITTY_SHELL_INTEGRATION:-}" ]]; then
        __O10K_HAS_TERMINAL_INTEGRATION=1
        __O10K_EMIT_OSC133=0
    else
        __O10K_EMIT_OSC133=1
    fi
}

__o10k_detect_terminal_integration

# ── OSC 133;C/D Semantic Prompts ──────────────────────────────────────────
# Separate gate from the OSC 133;A/B shell-integration flag above. The
# daemon mirrors [terminal.semantic_prompts].enabled into every prompt
# response (semantic_prompts); default is OFF until the first response.
__O10K_SEMANTIC_PROMPTS=0
__O10K_EMIT_133CD=0

__o10k_update_133cd() {
    __O10K_EMIT_133CD=0
    case "$__O10K_SHELL_INTEGRATION" in
        off)   return ;;
        force) __O10K_EMIT_133CD=1; return ;;
    esac
    (( __O10K_SEMANTIC_PROMPTS )) || return
    [[ -n "${TMUX:-}" ]] && return   # tmux does not forward 133
    case "${O10K_TERM:-}" in ghostty|foot|kitty|wezterm) ;; *) return ;; esac
    # Ghostty auto-injects its own bash integration, which emits 133;C/D.
    # Double emission corrupts prompt navigation — yield to it.
    #
    # The injected FUNCTION is the signal. GHOSTTY_SHELL_FEATURES is not:
    # Ghostty sets it identically whether shell-integration is `none` or
    # `detect`, because it is populated from `shell-integration-features` --
    # a different key listing which features are configured, not whether the
    # integration was injected. Testing it here meant this function always
    # returned, so 133;C/D never fired in Ghostty at all.
    declare -F __ghostty_precmd &>/dev/null && return
    __O10K_EMIT_133CD=1
}
__o10k_update_133cd

# ── Hook Broker ────────────────────────────────────────────────────────────
# Public API for tools (Mise, Atuin, Zoxide, etc.) to register callbacks
# Usage: o10k_hook_add <event> <function_name>
# Events: precmd, preexec, chpwd, shell_exit

declare -a __O10K_HOOKS_precmd=()
declare -a __O10K_HOOKS_preexec=()
declare -a __O10K_HOOKS_chpwd=()
declare -a __O10K_HOOKS_shell_exit=()

o10k_hook_add() {
    local event="$1" fn="$2"
    case "$event" in
        precmd)    __O10K_HOOKS_precmd+=("$fn") ;;
        preexec)   __O10K_HOOKS_preexec+=("$fn") ;;
        chpwd)     __O10K_HOOKS_chpwd+=("$fn") ;;
        shell_exit) __O10K_HOOKS_shell_exit+=("$fn") ;;
        *) echo "omarchy10k: unknown hook event: $event" >&2 ;;
    esac
}

o10k_hook_remove() {
    local event="$1" fn="$2"
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local new=()
    for f in "${hooks[@]}"; do
        [[ "$f" != "$fn" ]] && new+=("$f")
    done
    hooks=("${new[@]}")
}

__o10k_dispatch() {
    local event="$1"; shift
    local -n hooks="__O10K_HOOKS_${event}" 2>/dev/null || return
    local fn
    for fn in "${hooks[@]}"; do
        "$fn" "$@" 2>/dev/null
    done
}

# ── Daemon Lifecycle ───────────────────────────────────────────────────────

export O10K_PARENT_PID=$$

__o10k_start_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        if __o10k_socket_send '{"command":"status"}' >/dev/null 2>&1; then
            return 0
        fi
        rm -f "$__O10K_SOCKET"
    fi

    O10K_PARENT_PID=$$ "$__O10K_DAEMON_BIN" &>/dev/null &
    __O10K_DAEMON_PID=$!
    disown
    printf '%s\n' "$__O10K_DAEMON_PID" > "${__O10K_SOCKET_DIR}/omarchy10k-$$.pid" 2>/dev/null

    local i=0
    while [[ ! -S "$__O10K_SOCKET" ]] && (( i < 20 )); do
        sleep 0.1
        (( i++ ))
    done

    if [[ ! -S "$__O10K_SOCKET" ]]; then
        local hint_file="${__O10K_CACHE_DIR}/.first-run-hint-shown"
        if [[ ! -f "$hint_file" ]]; then
            echo "[omarchy10k] Daemon not running. Run 'omarchy10k doctor' for diagnostics." >&2
            touch "$hint_file" 2>/dev/null
        fi
    fi
}

__o10k_stop_daemon() {
    if [[ -S "$__O10K_SOCKET" ]]; then
        __o10k_socket_send '{"command":"shutdown"}' 2>/dev/null || true
        rm -f "$__O10K_SOCKET"
    fi
    rm -f "${__O10K_SOCKET_DIR}/omarchy10k-$$.pid" 2>/dev/null
}

# ── Bridge Coprocess ──────────────────────────────────────────────────────
# Persistent Rust process that holds a daemon connection and avoids
# fork/exec on every prompt render. Falls back to socket_send if unavailable.

__O10K_BRIDGE_PID=0

__o10k_start_bridge() {
    if (( __O10K_BRIDGE_PID > 0 )) && kill -0 "$__O10K_BRIDGE_PID" 2>/dev/null; then
        return 0
    fi

    # Restarting over a dead coprocess: close its fds first so they don't leak
    if (( __O10K_BRIDGE_PID > 0 )); then
        exec {__O10K_BRIDGE[0]}>&- {__O10K_BRIDGE[1]}>&- 2>/dev/null
    fi

    coproc __O10K_BRIDGE { "$__O10K_BIN" bridge --socket "$__O10K_SOCKET" 2>/dev/null; }
    __O10K_BRIDGE_PID=$!
}

# Best-effort drain of late-arriving coproc fields so a failed read cannot
# shift the request/response stream by one on the next request.
__o10k_bridge_drain() {
    local junk
    while IFS= read -r -d $'\0' -t 0.1 -u "${__O10K_BRIDGE[0]}" junk 2>/dev/null; do
        :
    done
}

__o10k_bridge_request() {
    local request="$1" cols="${2:-${COLUMNS:-80}}"
    if (( __O10K_BRIDGE_PID > 0 )) && kill -0 "$__O10K_BRIDGE_PID" 2>/dev/null; then
        echo "$request" >&"${__O10K_BRIDGE[1]}" 2>/dev/null || {
            __o10k_start_bridge
            echo "$request" >&"${__O10K_BRIDGE[1]}" 2>/dev/null || return 1
        }
        local left right threshold="" transient=""
        # NUL-framed fields: left, right, notify_threshold_ms (may be empty),
        # transient (may be empty)
        if ! IFS= read -r -d $'\0' -t 2 -u "${__O10K_BRIDGE[0]}" left 2>/dev/null; then
            # Left read failed — abort (caller falls back to socket send)
            # instead of consuming the next field's data.
            __o10k_bridge_drain
            return 1
        fi
        if IFS= read -r -d $'\0' -t 0.5 -u "${__O10K_BRIDGE[0]}" right 2>/dev/null; then
            IFS= read -r -d $'\0' -t 0.5 -u "${__O10K_BRIDGE[0]}" threshold 2>/dev/null \
                || __o10k_bridge_drain
            IFS= read -r -d $'\0' -t 0.5 -u "${__O10K_BRIDGE[0]}" transient 2>/dev/null \
                || __o10k_bridge_drain
        else
            # Right field lost — stream position uncertain, so drain the rest
            # (including any late-arriving right/threshold) and skip reading.
            right=""
            __o10k_bridge_drain
        fi
        if [[ -n "$left" ]]; then
            PS1="$left"
            __O10K_LAST_RIGHT="${right:-}"
            __o10k_set_notify_threshold "$threshold"
            __O10K_TRANSIENT="${transient:-}"
            # Bake the vanilla poor-man right rail into PS1 before the
            # instant-prompt cache write so cache and live PS1 agree.
            __o10k_apply_right_rail "$cols"
            { printf '%s' "$PS1" > "$__O10K_CACHE.$$.tmp" && mv "$__O10K_CACHE.$$.tmp" "$__O10K_CACHE"; } 2>/dev/null &
            disown "$!" 2>/dev/null || true
            # Bridge writes the side-channel flags before its response
            # fields; refresh immediately so the 133;C/D gate is current
            # without a one-render lag.
            __o10k_read_flags
            return 0
        fi
        __o10k_bridge_drain
    fi
    return 1
}

# Rate-limited (5s) daemon+bridge restart used when recovery finds a missing
# socket or a socket whose daemon no longer answers a status probe.
__o10k_try_restart() {
    local now="${EPOCHREALTIME:-0}"
    now="${now%%[.,]*}"
    (( now - ${__O10K_LAST_RESTART_ATTEMPT:-0} > 5 )) || return 0
    __O10K_LAST_RESTART_ATTEMPT="$now"
    rm -f "$__O10K_SOCKET"
    __o10k_start_daemon
    __o10k_start_bridge
}

# Portable Unix socket send — legacy fallback when bridge is unavailable
__o10k_socket_send() {
    local msg="$1"
    if command -v socat &>/dev/null; then
        echo "$msg" | socat -T2 - UNIX-CONNECT:"$__O10K_SOCKET"
    elif command -v python3 &>/dev/null; then
        python3 -c '
import socket, sys
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(2)
s.connect(sys.argv[1])
s.sendall((sys.argv[2] + "\n").encode())
data = b""
while True:
    chunk = s.recv(4096)
    if not chunk: break
    data += chunk
    if b"\n" in data: break
s.close()
sys.stdout.write(data.decode())
' "$__O10K_SOCKET" "$msg" 2>/dev/null
    else
        return 1
    fi
}

# ── Timing ─────────────────────────────────────────────────────────────────

__O10K_CMD_START=0
__O10K_CMD_DURATION=0
__O10K_LAST_CMD=""
__O10K_LAST_RIGHT=""
__O10K_NOTIFY_THRESHOLD="${O10K_NOTIFY_THRESHOLD:-10000}"
__O10K_NOTIFY_UNFOCUSED_ONLY=0
__O10K_HAS_NOTIFY_SEND=0
command -v omarchy-notification-send &>/dev/null && __O10K_HAS_NOTIFY_SEND=1
__O10K_TRANSIENT=""
__O10K_FLAGS="${__O10K_SOCKET}.flags"

__o10k_timer_start() {
    __O10K_CMD_START="${EPOCHREALTIME:-$(date +%s%N)}"
}

__o10k_timer_stop() {
    if [[ "$__O10K_CMD_START" == "0" ]]; then
        __O10K_CMD_DURATION=0
        return
    fi
    local now="${EPOCHREALTIME:-$(date +%s%N)}"
    # Normalize comma decimal separator to period (European locales)
    now="${now//,/.}"
    __O10K_CMD_START="${__O10K_CMD_START//,/.}"
    if [[ "$now" == *.* ]]; then
        local start_s="${__O10K_CMD_START%%.*}"
        local start_us="${__O10K_CMD_START##*.}"
        local now_s="${now%%.*}"
        local now_us="${now##*.}"
        start_us="${start_us}000000"; start_us="${start_us:0:6}"
        now_us="${now_us}000000"; now_us="${now_us:0:6}"
        __O10K_CMD_DURATION=$(( (now_s - start_s) * 1000 + (10#$now_us - 10#$start_us) / 1000 ))
    else
        __O10K_CMD_DURATION=0
    fi
    __O10K_CMD_START=0
}

# ── Chpwd Emulation ───────────────────────────────────────────────────────

__O10K_LAST_PWD="$PWD"

__o10k_check_chpwd() {
    if [[ "$PWD" != "$__O10K_LAST_PWD" ]]; then
        __O10K_LAST_PWD="$PWD"
        __o10k_dispatch chpwd
    fi
}

# ── Prompt Rendering ──────────────────────────────────────────────────────

__O10K_FALLBACK_PS1='\[\e[1;34m\]\w\[\e[0m\] \[\e[1;32m\]❯\[\e[0m\] '

# Percent-encode characters that are unsafe or would terminate a file:// URI
# early (space, %, #, ?) and drop control characters before emitting OSC 7.
__o10k_uri_encode() {
    local s="${1//[[:cntrl:]]/}"
    s="${s//%/%25}"
    s="${s// /%20}"
    s="${s//#/%23}"
    s="${s//\?/%3F}"
    printf '%s' "$s"
}

# Threshold 0 or empty means notifications are OFF (daemon-disabled must
# never fall back to the bootstrap default — the verified 0.2 no-op bug).
__o10k_set_notify_threshold() {
    local t="$1"
    if [[ -z "$t" || "$t" == "0" ]]; then
        __O10K_NOTIFY_THRESHOLD=0
    else
        __O10K_NOTIFY_THRESHOLD="$t"
    fi
}

# The bridge relays per-response config flags (semantic_prompts,
# notify_unfocused_only) through a side-channel file so the hot path keeps
# its frozen four-field NUL framing. Reads never fork.
__o10k_read_flags() {
    local f=""
    IFS= read -r f 2>/dev/null < "$__O10K_FLAGS" || f=""
    case "$f" in
        *semantic_prompts=1*) __O10K_SEMANTIC_PROMPTS=1 ;;
        *semantic_prompts=0*) __O10K_SEMANTIC_PROMPTS=0 ;;
    esac
    case "$f" in
        *notify_unfocused_only=1*) __O10K_NOTIFY_UNFOCUSED_ONLY=1 ;;
        *notify_unfocused_only=0*) __O10K_NOTIFY_UNFOCUSED_ONLY=0 ;;
    esac
    __o10k_update_133cd
}

# Focus detection (Hyprland): the terminal emulator containing this shell is
# the focused window when its pid is in our ancestor chain. Returns 1
# ("not focused" — notification allowed) when focus cannot be determined.
__o10k_terminal_focused() {
    local pid
    pid=$(hyprctl -j activewindow 2>/dev/null \
        | python3 -c 'import sys,json; print(json.load(sys.stdin).get("pid") or "")' 2>/dev/null) \
        || return 1
    [[ -n "$pid" ]] || return 1
    local cur=$$ ppid
    while (( cur > 1 )); do
        [[ "$cur" == "$pid" ]] && return 0
        ppid=$(command sed -n 's/^PPid:[[:space:]]*//p' "/proc/$cur/status" 2>/dev/null) || return 1
        [[ -n "$ppid" ]] || return 1
        cur="$ppid"
    done
    return 1
}

# Desktop notification for a long-running command. Prefers Omarchy's themed
# wrapper (notify-send-compatible); falls back to the sanitized OSC 777
# path. Honors [notifications].unfocused_only via the focus probe above.
__o10k_notify() {
    local title="Command finished"
    local body
    printf -v body '%s took %dms' "${__O10K_LAST_CMD:-command}" "$__O10K_CMD_DURATION"

    if (( __O10K_NOTIFY_UNFOCUSED_ONLY )) && __o10k_terminal_focused; then
        return
    fi

    if (( __O10K_HAS_NOTIFY_SEND )); then
        if omarchy-notification-send "$title" "$body" &>/dev/null; then
            return
        fi
    fi

    # Strip all C0 control characters (CR/LF/VT/FF/BEL/ESC/...) and
    # semicolons that could break OSC 777 framing
    body="${body//[[:cntrl:];]/}"
    printf '\033]777;notify;%s;%s\007' "$title" "$body"
}

# Escapes a string for JSON: strips control characters (they would corrupt
# the request stream) and escapes backslash/quote. Sets __O10K_ESCAPED.
__o10k_json_escape() {
    local s="${1//[[:cntrl:]]/}"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    __O10K_ESCAPED="$s"
}

# Builds the env allowlist JSON (0.1 env channel) with pure parameter
# expansions — zero subprocesses. Frozen allowlist (12 env keys + the three
# agent-signal keys for the 1.3 ai segment + the vi-mode key for the prompt
# character): only non-empty values are sent; unset variables are skipped.
# Sets __O10K_ENV_JSON.
__o10k_env_json() {
    local env_json="" k v esc
    for k in VIRTUAL_ENV CONDA_DEFAULT_ENV MISE_NODE_VERSION MISE_PYTHON_VERSION \
             MISE_RUBY_VERSION MISE_GO_VERSION MISE_RUST_VERSION IN_NIX_SHELL \
             DISTROBOX_ENTER_PATH container KUBECONFIG DIRENV_DIR \
             CLAUDE_CODE_ENTRYPOINT CODEX_SANDBOX CODEX_HOME; do
        v="${!k:-}"
        [[ -n "$v" ]] || continue
        esc="${v//[[:cntrl:]]/}"
        esc="${esc//\\/\\\\}"
        esc="${esc//\"/\\\"}"
        if [[ -z "$env_json" ]]; then
            env_json="\"$k\":\"$esc\""
        else
            env_json="$env_json,\"$k\":\"$esc\""
        fi
    done
    # Vi-mode signal (character segment): bash reports the current keymap in
    # KEYMAP. ble.sh keeps it set; vanilla bash only populates it inside
    # bind-based callbacks — when it is empty we emit nothing and the daemon
    # keeps the default prompt character.
    if [[ -n "${KEYMAP:-}" ]]; then
        v="${KEYMAP//[[:cntrl:]]/}"
        v="${v//\\/\\\\}"
        v="${v//\"/\\\"}"
        if [[ -z "$env_json" ]]; then
            env_json="\"vi_mode\":\"$v\""
        else
            env_json="$env_json,\"vi_mode\":\"$v\""
        fi
    fi
    __O10K_ENV_JSON="{$env_json}"
}

# ── Visible Width + Poor-Man Right Rail (vanilla bash) ────────────────────
# Sets __O10K_WIDTH to the display width of a prompt fragment, mirroring the
# daemon's strip_ansi_width rules: \x01/\x02 readline markers and raw
# SGR/OSC sequences count as zero. Codepoints are counted (not bytes);
# double-width CJK glyphs are the known miscount (rare in the rail).
__o10k_prompt_visible_width() {
    local s="$1" clean="" rest=""
    while [[ "$s" == *$'\x01'* ]]; do
        [[ "$s" == *$'\x02'* ]] || { s="${s%%$'\x01'*}"; break; }
        clean+="${s%%$'\x01'*}"
        s="${s#*$'\x02'}"
    done
    rest="$s"
    # Defensive: strip unwrapped CSI/OSC leftovers the same way the daemon
    # does (daemon output is always \x01/\x02-wrapped, so this is a no-op
    # in practice — but the fallback PS1 uses raw \[ \e[ \] text).
    while [[ "$rest" == *$'\e'* ]]; do
        clean+="${rest%%$'\e'*}"
        rest="${rest#*$'\e'}"
        case "$rest" in
            ']'*)
                if [[ "$rest" == *$'\a'* ]]; then rest="${rest#*$'\a'}"
                elif [[ "$rest" == *$'\e\\'* ]]; then rest="${rest#*$'\e\\'}"
                else rest=""; fi ;;
            '['*) rest="${rest#*[a-zA-Z]}" ;;
            *) rest="${rest#?}" ;;
        esac
    done
    clean+="$rest"
    __O10K_WIDTH="${#clean}"
}

# Poor-man RPS1 for vanilla bash: bash has no native right prompt, so the
# right rail is baked into PS1 as right-aligned padding on the line directly
# above the input line (a one-line prompt gains a dedicated rail line above
# it — the input position must stay after the left prompt). Padding uses the
# cols the prompt request already carries; the daemon gates the
# [prompt].right_prompt and frame-mode conditions (it sends `right` only when
# right_prompt is on and frames are off), and ble.sh is excluded here because
# it owns RPS1 natively.
# LIMITATION: the rail is positioned once per render from the cols of that
# render — there is no redraw-on-resize (no SIGWINCH re-render), so the rail
# drifts until the next prompt; the instant-prompt cache likewise carries the
# cols of the render that produced it. A rail that does not fit (gap < 1 col)
# is dropped for that render.
__o10k_apply_right_rail() {
    local cols="$1"
    [[ -n "${__O10K_LAST_RIGHT:-}" ]] || return 0
    if declare -F blehook &>/dev/null || [[ -n "${BLE_VERSION:-}" ]]; then
        return 0
    fi
    (( cols > 0 )) || return 0
    local right="$__O10K_LAST_RIGHT" pad=""
    __o10k_prompt_visible_width "$right"
    local rw=$__O10K_WIDTH
    (( rw < cols )) || return 0
    local ps1="$PS1" prefix="" rail_line=""
    if [[ "$ps1" == *$'\n'* ]]; then
        local head="${ps1%$'\n'*}" last="${ps1##*$'\n'}"
        if [[ "$head" == *$'\n'* ]]; then
            rail_line="${head##*$'\n'}"
            prefix="${head%$'\n'*}"$'\n'
        else
            rail_line="$head"
        fi
        __o10k_prompt_visible_width "$rail_line"
        local gap=$(( cols - __O10K_WIDTH - rw ))
        (( gap >= 1 )) || return 0
        printf -v pad '%*s' "$gap" ''
        PS1="${prefix}${rail_line}${pad}${right}"$'\n'"${last}"
    else
        local gap=$(( cols - rw ))
        (( gap >= 1 )) || return 0
        printf -v pad '%*s' "$gap" ''
        PS1="${pad}${right}"$'\n'"${ps1}"
    fi
}

__o10k_render_prompt() {
    local exit_code=$?

    # OSC 133;D — mark end of previous command output
    (( __O10K_EMIT_133CD )) && printf '\e]133;D;%d\a' "$exit_code"

    __o10k_timer_stop

    # Desktop notification for long-running commands. A threshold of 0 means
    # the daemon disabled notifications — never fall back to a default.
    if (( __O10K_NOTIFY_THRESHOLD > 0 && __O10K_CMD_DURATION > __O10K_NOTIFY_THRESHOLD )); then
        __o10k_notify
    fi

    printf '\033[?2026h'

    __o10k_check_chpwd
    __o10k_dispatch precmd

    printf '\033]9;4;0\007'

    # Recovery: probe a present socket before touching it — a healthy daemon's
    # socket is never deleted (only the bridge may have died), while a dead
    # daemon behind a stale socket is rm'd and restarted. Rate limited to 5s.
    if [[ -S "$__O10K_SOCKET" ]]; then
        if (( __O10K_BRIDGE_PID > 0 )) && kill -0 "$__O10K_BRIDGE_PID" 2>/dev/null; then
            : # socket present and bridge alive — nothing to recover
        elif __o10k_socket_send '{"command":"status"}' >/dev/null 2>&1; then
            __o10k_start_bridge
        else
            __o10k_try_restart
        fi
    else
        __o10k_try_restart
    fi

    if [[ -S "$__O10K_SOCKET" ]]; then
        local cols="${COLUMNS:-80}"
        local -a _jobs_arr=()
        mapfile -t _jobs_arr < <(jobs -p 2>/dev/null)
        local jobs_count=${#_jobs_arr[@]}

        local si_flag="true"
        (( __O10K_EMIT_OSC133 )) || si_flag="false"

        __o10k_read_flags

        # Fresh env snapshot per render (0.1 env channel) — pure parameter
        # expansions over the frozen 12-key allowlist, zero forks
        __o10k_env_json
        __o10k_json_escape "$PWD"
        local escaped_cwd="$__O10K_ESCAPED"
        local request
        printf -v request \
            '{"cwd":"%s","exit_code":%d,"cmd_duration_ms":%d,"cols":%d,"jobs":%d,"shell_integration":%s,"env":%s}' \
            "$escaped_cwd" "$exit_code" "$__O10K_CMD_DURATION" "$cols" "$jobs_count" "$si_flag" "$__O10K_ENV_JSON"

        # Try bridge first (no fork/exec in hot path)
        if __o10k_bridge_request "$request" "$cols"; then
            printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$(__o10k_uri_encode "$PWD")"
            printf '\033[?2026l'
            return
        fi

        # Fallback: socket send + parse-prompt
        local response
        response=$(__o10k_socket_send "$request" 2>/dev/null)

        if [[ -n "$response" ]]; then
            local left
            left=$(echo "$response" | "$__O10K_BIN" parse-prompt 2>/dev/null || echo "$response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('left',''))" 2>/dev/null)
            if [[ -n "$left" ]]; then
                PS1="$left"
                __O10K_LAST_RIGHT=$(echo "$response" | python3 -c "import sys,json; r=json.load(sys.stdin).get('right',''); print(r if r else '')" 2>/dev/null)
                __o10k_apply_right_rail "$cols"
                { printf '%s' "$PS1" > "$__O10K_CACHE.$$.tmp" && mv "$__O10K_CACHE.$$.tmp" "$__O10K_CACHE"; } 2>/dev/null &
                disown "$!" 2>/dev/null || true

                local threshold sem unf transient_str
                threshold=$(echo "$response" | python3 -c "import sys,json; t=json.load(sys.stdin).get('notify_threshold_ms'); print(t if t else '')" 2>/dev/null)
                __o10k_set_notify_threshold "$threshold"
                sem=$(echo "$response" | python3 -c 'import sys,json; print(1 if json.load(sys.stdin).get("semantic_prompts") else 0)' 2>/dev/null)
                unf=$(echo "$response" | python3 -c 'import sys,json; print(1 if json.load(sys.stdin).get("notify_unfocused_only") else 0)' 2>/dev/null)
                transient_str=$(echo "$response" | python3 -c 'import sys,json; t=json.load(sys.stdin).get("transient"); print(t if t else "")' 2>/dev/null)
                [[ -n "$sem" ]] && __O10K_SEMANTIC_PROMPTS="$sem"
                [[ -n "$unf" ]] && __O10K_NOTIFY_UNFOCUSED_ONLY="$unf"
                __O10K_TRANSIENT="${transient_str:-}"
                __o10k_update_133cd

                printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$(__o10k_uri_encode "$PWD")"
                printf '\033[?2026l'
                return
            fi
        fi
    fi

    PS1="$__O10K_FALLBACK_PS1"
    printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "$(__o10k_uri_encode "$PWD")"
    printf '\033[?2026l'
}
# Transient prompt for vanilla bash: replace the previous prompt with the
# daemon's transient form using line-overwrite only (no ble.sh, no alternate
# screen). The prompt may span multiple lines (frames, blank_line) — the
# cursor sits at column 0 of the line below the echoed command, so the
# prompt starts exactly (newlines in PS1 + 1) lines up; every prompt line is
# cleared and the transient character lands on the last one. p10k/ble.sh
# parity: the executed command stays visible after the transient character
# when it fits on one line; long, multi-line or control-bearing commands
# fall back to a clean erase. \x01/\x02 markers are stripped — they are
# readline-only conventions and must not leak into the output stream.
# Cursor-up + overwrite only, so the collapsed prompt survives scrollback.
# (ble.sh shells never reach this — their transient is prompt_ps1_final.)
__o10k_emit_transient() {
    local cmd="${1:-}"
    [[ -n "${__O10K_TRANSIENT:-}" ]] || return 0
    local t="${__O10K_TRANSIENT//$'\x01'/}"
    t="${t//$'\x02'/}"
    local n=1 tmp="$PS1"
    while [[ "$tmp" == *$'\n'* ]]; do
        (( n++ ))
        tmp="${tmp#*$'\n'}"
    done
    if (( n == 1 )); then
        printf '\033[1A\r'
    else
        printf '\033[%dA\r' "$n"
        local i=1
        while (( i < n )); do
            printf '\033[K\n'
            (( i++ ))
        done
    fi
    if [[ -n "$cmd" && "$cmd" != *$'\n'* && "$cmd" != *[![:print:]]* ]] \
        && (( ${#cmd} + ${#t} + 1 < ${COLUMNS:-80} )); then
        # The daemon's transient renders as "{char} " — the trailing space
        # sits before the closing OSC. Add a separator space only when the
        # fully-stripped visible text does not already end with one.
        local vis="" s="$t"
        while [[ "$s" == *$'\e'* ]]; do
            vis+="${s%%$'\e'*}"
            s="${s#*$'\e'}"
            case "$s" in
                ']'*)
                    if [[ "$s" == *$'\a'* ]]; then s="${s#*$'\a'}"
                    elif [[ "$s" == *$'\e\\'* ]]; then s="${s#*$'\e\\'}"
                    else s=""; fi ;;
                '['*) s="${s#*[a-zA-Z]}" ;;
                *) s="${s#?}" ;;
            esac
        done
        vis+="$s"
        if [[ -n "$vis" && "$vis" != *" " ]]; then
            printf '%s %s\033[K' "$t" "$cmd"
        else
            printf '%s%s\033[K' "$t" "$cmd"
        fi
    else
        printf '%s\033[K' "$t"
    fi
    printf '\r\033[B'
}


# ── Preexec ────────────────────────────────────────────────────────────────

__O10K_PREEXEC_READY=0

__o10k_preexec() {
    # Omarchy10k owns preexec handling and keeps promptvars disabled. Clear any
    # PS0 expression restored after .bashrc (notably Ghostty's injected Bash
    # hook) before Bash expands it as literal command-prefix text.
    PS0=''

    [[ "$__O10K_PREEXEC_READY" == "1" ]] || return
    __O10K_PREEXEC_READY=0

    __O10K_LAST_CMD="$1"

    # Transient prompt (non-ble): overwrite the previous prompt with the
    # daemon's transient string — multiline-aware (frames collapse too) and
    # p10k/ble.sh-parity (the executed command stays visible when it fits).
    __o10k_emit_transient "$1"

    # OSC 133;C — mark start of command output
    (( __O10K_EMIT_133CD )) && printf '\e]133;C\a'
    printf '\033]9;4;3\007'
    __o10k_timer_start
    __o10k_dispatch preexec "$1"
}

# ── Installation ───────────────────────────────────────────────────────────

__o10k_install_hooks() {
    if declare -F blehook &>/dev/null; then
        __o10k_install_blesh_hooks
    else
        __o10k_install_vanilla_hooks
    fi
}

__o10k_install_blesh_hooks() {
    blehook PRECMD+='__o10k_render_prompt'
    blehook PREEXEC+='__o10k_preexec_blesh'
    blehook CHPWD+='__o10k_dispatch chpwd'

    bleopt prompt_ps1_transient='always'

    # Right prompt support via ble.sh
    blehook PRECMD+='__o10k_update_rps1'

    blehook PRECMD+='__O10K_PREEXEC_READY=1'
}

__o10k_preexec_blesh() {
    # OSC 133;C
    (( __O10K_EMIT_133CD )) && printf '\e]133;C\a'
    __O10K_LAST_CMD="$1"
    printf '\033]9;4;3\007'
    __o10k_timer_start
    __o10k_dispatch preexec "$1"
}

__o10k_update_rps1() {
    if [[ -n "${__O10K_LAST_RIGHT:-}" ]]; then
        bleopt prompt_rps1="$__O10K_LAST_RIGHT"
    else
        bleopt prompt_rps1=""
    fi
    # Daemon-provided transient string replaces the collapsed prompt via
    # ble.sh's prompt_ps1_final; empty keeps the shipped vanish behavior.
    bleopt prompt_ps1_final="$__O10K_TRANSIENT"
}

__o10k_install_vanilla_hooks() {
    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        PROMPT_COMMAND=('__o10k_render_prompt' "${PROMPT_COMMAND[@]}")
    elif [[ -n "${PROMPT_COMMAND:-}" ]]; then
        PROMPT_COMMAND="__o10k_render_prompt;${PROMPT_COMMAND}"
    else
        PROMPT_COMMAND='__o10k_render_prompt'
    fi

    local existing_trap
    existing_trap=$(trap -p DEBUG 2>/dev/null | command sed "s/trap -- '\\(.*\\)' DEBUG/\\1/")
    # Pass the triggering command as an argument: by the time the handler
    # body runs, BASH_COMMAND already reflects the handler's own commands.
    if [[ -n "$existing_trap" ]]; then
        trap '__o10k_preexec "$BASH_COMMAND"; '"$existing_trap" DEBUG
    else
        trap '__o10k_preexec "$BASH_COMMAND"' DEBUG
    fi

    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        PROMPT_COMMAND+=('__O10K_PREEXEC_READY=1')
    else
        PROMPT_COMMAND="${PROMPT_COMMAND};__O10K_PREEXEC_READY=1"
    fi
}

# Test harness: O10K_HARNESS_ONLY=1 stops after the function definitions —
# no daemon/bridge/watchdog startup, no hook installation, no EXIT trap.
# Used by tests/vanilla_transient_test.sh to exercise the prompt functions
# standalone in a plain bash fixture.
[[ -n "${O10K_HARNESS_ONLY:-}" ]] && return 0

# ── Shell Exit ─────────────────────────────────────────────────────────────

__o10k_cleanup() {
    __o10k_dispatch shell_exit
    # Kill bridge coprocess
    if (( __O10K_BRIDGE_PID > 0 )); then
        kill "$__O10K_BRIDGE_PID" 2>/dev/null
    fi
    __o10k_stop_daemon
}

trap __o10k_cleanup EXIT

# ── Theme Env (rice layer) ─────────────────────────────────────────────────
# The Omarchy theme engine renders o10k-env.sh (fzf/eza/less/lazygit colors)
# on every theme switch at a stable path. Re-source it when its mtime moves
# so running shells adopt the new palette without restart. One stat per
# prompt when unchanged.

__O10K_THEME_ENV="${XDG_STATE_HOME:-$HOME/.local/state}/omarchy/current/theme/o10k-env.sh"
__O10K_THEME_ENV_STAMP="${__O10K_CACHE_DIR}/env.stamp"

__o10k_source_theme_env() {
    [[ -f "$__O10K_THEME_ENV" ]] || return 0
    if [[ ! -f "$__O10K_THEME_ENV_STAMP" || "$__O10K_THEME_ENV" -nt "$__O10K_THEME_ENV_STAMP" ]]; then
        # The theme engine rewrites this file during the next-theme → theme
        # swap; a read racing that rewrite can yield a truncated file. Only
        # commit the stamp when the result is sane — otherwise the next
        # prompt retries (one-render self-heal instead of stuck-empty env).
        if source "$__O10K_THEME_ENV" 2>/dev/null && [[ -n "${FZF_DEFAULT_OPTS:-}" ]]; then
            touch "$__O10K_THEME_ENV_STAMP" 2>/dev/null
        fi
    fi
}
o10k_hook_add precmd __o10k_source_theme_env
__o10k_source_theme_env

# ── Idle-Shell Watchdog ────────────────────────────────────────────────────
# Precmd recovery only fires when a prompt draws — an idle shell whose
# daemon was killed (crash, deploy, OOM) stays dark, and the Control Center
# bar widget reports offline until the user presses a key. This background
# loop polls the daemon's pid file (one kill -0 builtin per tick, zero
# forks) and respawns daemon+bridge via the 5s-rate-limited restart when it
# dies. $$ inside the subshell is the parent shell's PID, so the loop self-
# terminates when the owning shell exits.

__o10k_watchdog() {
    local pidfile="${__O10K_SOCKET_DIR}/omarchy10k-$$.pid"
    local dp
    while kill -0 "$$" 2>/dev/null; do
        sleep 10
        [[ -s "$pidfile" ]] || continue
        IFS= read -r dp < "$pidfile" 2>/dev/null || continue
        (( dp > 0 )) || continue
        # Daemon-only respawn: a bridge started here would live inside this
        # subshell and orphan. The parent shell's precmd recovery rebuilds
        # its own bridge on the next prompt.
        if ! kill -0 "$dp" 2>/dev/null; then
            rm -f "$__O10K_SOCKET"
            __o10k_start_daemon
        fi
    done
}

__o10k_watchdog &
disown
# ── Shell Layer (baked policy) ─────────────────────────────────────────────
# Policy was resolved once by `omarchy10k init bash` from [shell.layer] in
# config.toml and baked into __O10K_LAYER_POLICY / __O10K_LAYER_OVERRIDES_<name>
# (printed before this body; defaults to extend when sourced directly). This
# section applies only the CONTESTED claims: platform signature matched ->
# defer (the platform owns it); undefined -> define o10k's version; a user
# definition (non-matching) is always left alone. Nothing is unset or
# unaliased — only unhooked. `omarchy10k layer` prints the full claim map.

declare -a __O10K_DISPLACED=()

# Prompt handoff at init: unhook starship's and Ghostty's prompt hooks from
# PROMPT_COMMAND (both array and string shapes) and neutralize PS0, so the
# first prompt is already ours. Displacements are recorded, nothing is unset
# — revert by removing the init line from .bashrc (starship takes over).
__o10k_prompt_handoff() {
    local i
    if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
        for i in "${!PROMPT_COMMAND[@]}"; do
            if [[ "${PROMPT_COMMAND[$i]}" == *starship_precmd* || "${PROMPT_COMMAND[$i]}" == *__ghostty_hook* ]]; then
                __O10K_DISPLACED+=("${PROMPT_COMMAND[$i]}")
                PROMPT_COMMAND[$i]="${PROMPT_COMMAND[$i]//starship_precmd/:}"
                PROMPT_COMMAND[$i]="${PROMPT_COMMAND[$i]//__ghostty_hook/:}"
            fi
        done
    elif [[ -n "${PROMPT_COMMAND:-}" ]]; then
        if [[ "${PROMPT_COMMAND}" == *starship_precmd* || "${PROMPT_COMMAND}" == *__ghostty_hook* ]]; then
            __O10K_DISPLACED+=("${PROMPT_COMMAND}")
            PROMPT_COMMAND="${PROMPT_COMMAND//starship_precmd/:}"
            PROMPT_COMMAND="${PROMPT_COMMAND//__ghostty_hook/:}"
        fi
    fi
    # Ghostty's injected hook expands PS0; the adapter owns preexec handling.
    PS0=''
}

# ls — extend Omarchy's long-format eza with --git; define o10k's short
# format only when nothing owns ls; a non-matching (user) alias wins untouched.
__p="${__O10K_LAYER_OVERRIDES_ls:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off ]]; then
    if [[ "${BASH_ALIASES[ls]:-}" == *eza* && "${BASH_ALIASES[ls]:-}" == *--group-directories-first* ]]; then
        [[ "$__p" == extend ]] && alias ls='eza -lh --group-directories-first --icons=auto --git'
    elif [[ -z "${BASH_ALIASES[ls]:-}" ]] && command -v eza &>/dev/null; then
        alias ls='eza --icons=auto --group-directories-first'
    fi
fi

# lt — Omarchy's tree alias is strictly richer: defer when defined (platform
# or user), define o10k's version only when lt is unclaimed.
__p="${__O10K_LAYER_OVERRIDES_lt:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off && -z "${BASH_ALIASES[lt]:-}" ]] && command -v eza &>/dev/null; then
    alias lt='eza --tree --level=2 --icons=auto'
fi

# cd — Omarchy wraps cd with zd()/zoxide: defer entirely when present,
# initialize zoxide --cmd cd only when cd is completely unclaimed.
__p="${__O10K_LAYER_OVERRIDES_cd:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off ]] && ! declare -F zd &>/dev/null && ! declare -F _zoxide &>/dev/null \
    && [[ -z "${BASH_ALIASES[cd]:-}" ]] && ! declare -F cd &>/dev/null \
    && command -v zoxide &>/dev/null; then
    eval "$(zoxide init bash --cmd cd)"
fi

# fzf keys — Omarchy sources fzf key-bindings: skip when __fzf_history__ is
# already bound, wire fzf's integration only when it is not.
__p="${__O10K_LAYER_OVERRIDES_fzf_keys:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off ]] && ! declare -F __fzf_history__ &>/dev/null && command -v fzf &>/dev/null; then
    eval "$(fzf --bash 2>/dev/null)" || true
fi

# MANPAGER — keep the platform's bat man-pager; define o10k's (with a plain
# less fallback) only when unset.
__p="${__O10K_LAYER_OVERRIDES_manpager:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off && -z "${MANPAGER:-}" ]] && command -v bat &>/dev/null; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p 2>/dev/null || less'"
fi

# BAT_THEME — the platform's ansi inherits the theme-synced terminal palette:
# skip whenever set; fall back to ansi (never a hardcoded theme guess) when
# unset. The rice layer may still theme it via [rice] bat_theme.
__p="${__O10K_LAYER_OVERRIDES_bat_theme:-${__O10K_LAYER_POLICY:-extend}}"
if [[ "$__p" != off && -z "${BAT_THEME:-}" ]] && command -v bat &>/dev/null; then
    export BAT_THEME=ansi
fi
unset __p

# ── Modern CLI Layer ────────────────────────────────────────────────────────
# Aliases and tool inits (eza/bat/zoxide/atuin/fzf/yazi). Installed by
# install.sh; set O10K_NO_TOOLS=1 to skip.

[[ -z "${O10K_NO_TOOLS:-}" && -f "${HOME}/.config/omarchy10k/tools.sh" ]] \
    && source "${HOME}/.config/omarchy10k/tools.sh"

# ── Init ───────────────────────────────────────────────────────────────────

[[ -d "$__O10K_CACHE_DIR" ]] || mkdir -p "$__O10K_CACHE_DIR" 2>/dev/null

__o10k_start_daemon
__o10k_start_bridge
__o10k_prompt_handoff
__o10k_install_hooks

# First-run intro (3.3): background and non-blocking. Skipped by the marker
# file or O10K_NO_INTRO; the CLI itself exits silently when the daemon is
# down (marker stays unwritten so the next shell retries).
__o10k_intro_launch() {
    [[ -n "${O10K_NO_INTRO:-}" ]] && return 0
    [[ -f "${XDG_STATE_HOME:-$HOME/.local/state}/omarchy10k/intro_shown" ]] && return 0
    ( "$__O10K_BIN" intro >/dev/tty 2>/dev/null & ) 2>/dev/null
}
__o10k_intro_launch
