# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-delta.gitconfig.tpl
# Regenerated on every theme switch. Opt-in wiring — add to ~/.gitconfig:
#
#     [include]
#         path = "~/.local/state/omarchy/current/theme/o10k-delta.gitconfig"
#
# Place the include AFTER any user [delta] settings: git config applies
# later values over earlier ones, so this file acts as the base layer while
# anything the user sets after it still wins. (GIT_CONFIG_SYSTEM can carry
# the same path.) Inert until included; doctor reports delta itself absent.

[delta]
    features = o10k

[delta "o10k"]
    # Palette roles mirror o10k-lazygit.yml.tpl. Hex substitutions are
    # quoted: git config treats a bare # as a comment.
    file-style = "{{ accent }} bold"
    hunk-header-style = "{{ accent }}"
    hunk-header-file-style = "{{ muted }}"
    minus-style = "normal {{ red }}"
    minus-emphasis-style = "{{ red }} bold"
    plus-style = "normal {{ green }}"
    plus-emphasis-style = "{{ green }} bold"
    blame-palette = "{{ background }} {{ lighter_background }} {{ darker_background }}"
