# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-foot.ini.tpl
# Regenerated on every theme switch; included by ~/.config/foot/foot.ini
# (include=~/.local/state/omarchy/current/theme/o10k-foot.ini under [main]).
#
# Only theme-varying, NON-color-personality beyond the cursor lives here.
# Omarchy's own theme include owns background, foreground, and palette —
# emitting those here would fight the platform. This file re-asserts only
# the cursor colors (foot 1.27 keeps them under [colors]) so the cursor
# follows the Omarchy accent. The template engine is a flat sed pass (no
# conditionals), so per-mode opacity is not expressible; this file stays
# minimal rather than inventing syntax.
#
# foot processes includes at the directive's position and later values win,
# so this include must stay after Omarchy's theme include in foot.ini.

[colors]
# Cursor text/cursor-block pair: accent text on the theme background.
cursor={{ accent_strip }} {{ background_strip }}
