# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-yazi-theme.toml.tpl
# Regenerated on every theme switch. Yazi overlays this on its shipped
# defaults — partial files are fine.

[mgr]
cwd = { fg = "{{ cyan }}" }
hovered = { fg = "{{ foreground }}", bg = "{{ lighter_background }}" }
preview_hovered = { bg = "{{ lighter_background }}" }
find_focused = { fg = "{{ background }}", bg = "{{ accent }}" }
border = { fg = "{{ muted }}" }

[mode]
normal_main = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
normal_alt = { fg = "{{ accent }}", bg = "{{ lighter_background }}" }
select_main = { fg = "{{ background }}", bg = "{{ green }}", bold = true }
select_alt = { fg = "{{ green }}", bg = "{{ lighter_background }}" }
unset_main = { fg = "{{ background }}", bg = "{{ red }}", bold = true }
unset_alt = { fg = "{{ red }}", bg = "{{ lighter_background }}" }

[input]
border = { fg = "{{ accent }}" }
value = { fg = "{{ foreground }}" }
selected = { bg = "{{ lighter_background }}" }

[confirm]
border = { fg = "{{ accent }}" }
title = { fg = "{{ accent }}" }

[which]
mask = { bg = "{{ darker_background }}" }
cand = { fg = "{{ cyan }}" }
rest = { fg = "{{ muted }}" }
desc = { fg = "{{ foreground }}" }
separator = "  "
selected = { fg = "{{ background }}", bg = "{{ accent }}" }

[filetype]
rules = [
  { name = "*/", fg = "{{ accent }}" },
  { name = "*.{png,jpg,jpeg,gif,webp,avif,svg}", fg = "{{ magenta }}" },
  { name = "*.{mp4,mkv,webm,avi,mov}", fg = "{{ bright_magenta }}" },
  { name = "*.{mp3,flac,ogg,wav}", fg = "{{ bright_cyan }}" },
  { name = "*.{zip,tar,gz,xz,zst,7z,rar}", fg = "{{ yellow }}" },
  { name = "*.{rs,go,c,cpp,h,py,js,ts,tsx,rb,sh,bash}", fg = "{{ green }}" },
  { name = "*", fg = "{{ foreground }}" },
]
