#!/bin/bash
# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-env.sh.tpl
# Regenerated on every theme switch; re-sourced live by the omarchy10k
# Bash adapter (per-prompt mtime check). Colors come from the active theme.

# ── fzf ─────────────────────────────────────────────────────────────────────
export FZF_DEFAULT_OPTS="
  --color=bg:{{ background }},bg+:{{ lighter_background }},fg:{{ foreground }},fg+:{{ bright_foreground }},hl:{{ accent }},hl+:{{ accent }},pointer:{{ accent }},marker:{{ green }},spinner:{{ accent }},header:{{ muted }},info:{{ muted }},border:{{ muted }},prompt:{{ accent }},query:{{ foreground }},preview-fg:{{ foreground }},preview-bg:{{ background }},gutter:{{ background }}
  --border=rounded --pointer=❯ --marker=✓"
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"

# ── eza ─────────────────────────────────────────────────────────────────────
export EZA_COLORS="di=38;2;{{ accent_rgb }}:fi=38;2;{{ foreground_rgb }}:ln=38;2;{{ cyan_rgb }}:or=38;2;{{ red_rgb }}:ex=38;2;{{ green_rgb }}:xx=38;2;{{ dark_foreground_rgb }}:da=38;2;{{ dark_foreground_rgb }}:sn=38;2;{{ dark_foreground_rgb }}:sb=38;2;{{ muted_rgb }}:ga=38;2;{{ green_rgb }}:gm=38;2;{{ yellow_rgb }}:gd=38;2;{{ red_rgb }}:gv=38;2;{{ cyan_rgb }}:gt=38;2;{{ accent_rgb }}"

# ── man via less ────────────────────────────────────────────────────────────
export LESS_TERMCAP_md=$'\e[1;38;2;{{ accent_rgb }}m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_us=$'\e[4;38;2;{{ cyan_rgb }}m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_so=$'\e[48;2;{{ lighter_background_rgb }}m\e[38;2;{{ bright_foreground_rgb }}m'
export LESS_TERMCAP_se=$'\e[0m'

# ── bat ─────────────────────────────────────────────────────────────────────
# bat syntax themes are named bundles, not palettes — pick the closest match
# for the theme's light/dark mode. True per-theme syntax bundles are a later
# generator feature.
if [[ "{{ mode }}" == "light" ]]; then
    export BAT_THEME="Catppuccin Latte"
else
    export BAT_THEME="Catppuccin Mocha"
fi

# ── lazygit ──────────────────────────────────────────────────────────────────
# Theme layer first, user config second — later files override earlier ones.
export LG_CONFIG_FILE="$HOME/.local/state/omarchy/current/theme/o10k-lazygit.yml,${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/config.yml"
