#!/bin/bash
# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-blesh.bash.tpl
# Regenerated on every theme switch. Sourced by the omarchy10k Bash adapter
# ONLY when ble.sh is active (BLE_VERSION set) — inert on vanilla bash.
# Faces map ble.sh syntax categories onto o10k palette roles
# (platform-coexistence spec §6). Additive theming of an optional component;
# ble.sh is never the spine.

if [[ -n "${BLE_VERSION:-}" ]]; then
    ble-face -s syntax_command  'fg={{ accent }}'    # commands → accent
    ble-face -s syntax_filename 'fg={{ blue }}'      # valid paths → blue
    ble-face -s syntax_quoted   'fg={{ green }}'     # strings → green
    ble-face -s syntax_number   'fg={{ yellow }}'    # numbers → yellow
    ble-face -s syntax_varname  'fg={{ accent }}'    # variables → accent
    ble-face -s syntax_expr     'fg={{ foreground }}'  # options/expr → foreground
    ble-face -s syntax_comment  'fg={{ muted }}'     # comments → muted
    ble-face -s syntax_error    'fg={{ red }}'       # syntax errors → red
    ble-face -s auto_complete   'fg={{ muted }}'     # ghost suggestions → muted
fi
