# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-ghostty.conf.tpl
# Regenerated on every theme switch; included by ~/.config/ghostty/config
# (config-file = ?"~/.local/state/omarchy/current/theme/o10k-ghostty.conf").
#
# Only theme-varying, NON-color personality lives here. Omarchy's own theme
# include owns background, foreground, and palette — emitting those here
# would fight the platform. The template engine is a flat sed pass (no
# conditionals), so per-mode opacity is not expressible; this file stays
# minimal rather than inventing syntax.
#
# Ghostty applies later config-file includes over earlier ones, so this
# include must stay after Omarchy's theme include in ~/.config/ghostty/config.

cursor-color = {{ accent }}
