# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-cava.config.tpl
# Regenerated on every theme switch. Symlinked from ~/.config/cava/config.

[general]
bar_width = 2
bar_spacing = 1

[color]
background = '{{ background }}'
foreground = '{{ foreground }}'
method = gradient
gradient = 1
gradient_count = 4
gradient_color_1 = '{{ accent }}'
gradient_color_2 = '{{ bright_blue }}'
gradient_color_3 = '{{ cyan }}'
gradient_color_4 = '{{ bright_magenta }}'
