# Auto-generated by the Omarchy theme engine — do not edit manually.
# Template: ~/.config/omarchy/themed/o10k-lazygit.yml.tpl
# Regenerated on every theme switch. Loaded via LG_CONFIG_FILE (exported in
# o10k-env.sh) BEFORE the user's config.yml — user values win.

gui:
  theme:
    activeBorderColor:
      - "{{ accent }}"
      - bold
    inactiveBorderColor:
      - "{{ muted }}"
    searchingActiveBorderColor:
      - "{{ yellow }}"
      - bold
    optionsTextColor:
      - "{{ blue }}"
    selectedLineBgColor:
      - "{{ lighter_background }}"
    inactiveViewSelectedLineBgColor:
      - "{{ selection }}"
    cherryPickedCommitFgColor:
      - "{{ blue }}"
    cherryPickedCommitBgColor:
      - "{{ magenta }}"
    markedBaseCommitFgColor:
      - "{{ cyan }}"
    markedBaseCommitBgColor:
      - "{{ selection }}"
    unstagedChangesColor:
      - "{{ red }}"
    defaultFgColor:
      - "{{ foreground }}"
