# Auto-generated by Omarchy theme system — do not edit manually.
# This file is regenerated on every theme switch.
# To override colors, use [theme.custom] in ~/.config/omarchy10k/config.toml

[colors]
accent = "{{ accent }}"
foreground = "{{ foreground }}"
dark_foreground = "{{ dark_foreground }}"
bright_foreground = "{{ bright_foreground }}"
background = "{{ background }}"
dark_background = "{{ dark_background }}"
lighter_background = "{{ lighter_background }}"
muted = "{{ muted }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
mode = "{{ mode }}"
